### PR TITLE
Fix segfault when creating payments

### PR DESCRIPTION
**Pull request by eugeneius**
Closing the memory-mapped file too early was causing curl to read invalid memory and segfault.

### CODE REVIEW

**Comment by steobrien** [comment]
:shipit:

**Comment by eugeneius** [comment]
It's been 3 years since I opened this pull request; I don't think it's going to get merged any time soon.

Xero have [a fork of this project](https://github.com/XeroAPI/XeroOAuth-PHP) that is actively maintained, and this patch was accepted there a while ago: https://github.com/XeroAPI/XeroOAuth-PHP/pull/12

**Comment by steobrien** [comment]
:cry:

**Comment by buffermet** [comment]
Thanks for saving me a cluster headache :heart:

**Comment by buffermet** [comment]
I find it hard to believe that a patch like this has not been implemented yet.

**Comment by eugeneius** [comment]
I'm glad you found this useful @yungtravla - you might want to consider switching to https://github.com/calcinai/xero-php though, which is actively maintained.

**Pull request closed without merging**
